# Generated by Django 3.0.6 on 2020-07-11 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('desc', models.TextField()),
                ('catg', models.CharField(max_length=50, null=True)),
                ('status', models.IntegerField(default='open', max_length=50, null=True)),
                ('img_url', models.CharField(max_length=200, null=True)),
                ('dateTime', models.CharField(max_length=50)),
                ('starting_bid', models.IntegerField()),
                ('current_bid', models.IntegerField()),
                ('author_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('listing_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.Listings')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('listing_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.Listings')),
                ('user_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
